name: Build Pack

on:
  push:
    branches:
    - main
    # tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
    # - 'v*'

jobs:
  pack: 
    runs-on: ${{matrix.os}}
  
    strategy:
      matrix:
        os: [ macOS-latest] 

    steps:
      # 第一步：下载源码（CI/CD拉取代码到自己的本地）
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      # 第二步：打包构建
      - name: Install
        run: |
          npm run install
      
      - name: build mac app
        run: |
          npm run pack-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup artifacts for macosZ
        run: |
          npx rimraf "packages/**/packs/!(*.dmg)"
      
      # 上传构建产物
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: packages/**/packs

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "packages/**/packs/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
