name: Build Pack

on:
  push:
    branches:
    - main

jobs:
  pack: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macOS-latest] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm run install
        npm run pack-mac
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: packages/*/dist
